//Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Nour",
    "email": "Admin@gmail.com",
    "password": "123456789",
    "confPassword": "123456789",
    "role": "admin",

}
###
// get All Users 
GET http://localhost:5000/users

###
//session 
GET http://localhost:5000/me

###
//login 
POST http://localhost:5000/login
Content-Type: application/json
{
    "email": "nour@gmail.com",
    "password": "123456789"
}
